version: '3.4'

services:

  portainer:
    image: portainer/portainer-ce


  articlemongodb:
    image: mongo

  articles.api:
    image: ${DOCKER_REGISTRY-}articlesapi
    build:
      context: .
      dockerfile: Services/Articles/Articles.API/Dockerfile
      

  usermongodb:
    image: mongo

  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: Services/Users/Users.API/Dockerfile


  inventorydb:
    image: redis:alpine

  inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: Services/Inventory/Inventory.API/Dockerfile


  transportdb:
    image: redis:alpine

  transport.api:
    image: ${DOCKER_REGISTRY-}transportapi
    build:
      context: .
      dockerfile: Services/Transport/Transport.API/Dockerfile


  deliverydb:
    image: redis:alpine

  deliveries.api:
    image: ${DOCKER_REGISTRY-}deliveriesapi
    build:
      context: .
      dockerfile: Services/Deliveries/Deliveries.API/Dockerfile

      
  vehicledb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  vehicles.api:
    image: ${DOCKER_REGISTRY-}vehicleapi
    build:
      context: .
      dockerfile: Services/Vehicles/Vehicles.API/Dockerfile

      
  bikedb:
    image: postgres

  pgadmin_bike:
    image: dpage/pgadmin4

  bikes.api:
    image: ${DOCKER_REGISTRY-}bikesapi
    build:
      context: .
      dockerfile: Services/Bikes/Bikes.API/Dockerfile


volumes:
  mongo_data:
  user_mongo_data:
  portainer_data:
  postgres_data:
  postgres_bike_data:
  pgadmin_data:
  pgadmin_bike_data:





