version: '3.4'

services:

  articlemongodb:
    container_name : articlemongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  articles.api:
    container_name : articles.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoSettings:ConnectionString=mongodb://articlemongodb:27017"
    depends_on:
      - articlemongodb
    ports:
      - "8000:80"

  usermongodb:
    container_name : usermongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - user_mongo_data:/data/db

  users.api:
    container_name : users.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoSettings:ConnectionString=mongodb://usermongodb:27017"
    depends_on:
      - usermongodb
    ports:
      - "8500:80"

