version: '3.4'

services:

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


  articlemongodb:
    container_name : articlemongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  articles.api:
    container_name : articles.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoSettings:ConnectionString=mongodb://articlemongodb:27017"
    depends_on:
      - articlemongodb
    ports:
      - "8000:80"


  usermongodb:
    container_name : usermongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - user_mongo_data:/data/db

  users.api:
    container_name : users.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoSettings:ConnectionString=mongodb://usermongodb:27017"
    depends_on:
      - usermongodb
    ports:
      - "8500:80"


  inventorydb:
    container_name: inventorydb
    restart: always
    ports:
      - "6379:6379"

  inventory.api:
    container_name: inventory.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RedisSettings:ConnectionString=inventorydb:6379"
    depends_on:
      - inventorydb
    ports:
      - "8001:80"


  transportdb:
    container_name: transportdb
    restart: always
    ports:
      - "6380:6379"

  transport.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RedisSettings:ConnectionString=transportdb:6379"
    ports:
      - "8501:80"


  deliverydb:
    container_name: deliverydb
    restart: always
    ports:
      - "6381:6379"

  deliveries.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=deliverydb:6379"
    ports:
      - "8502:80"


  vehicledb:
    container_name : vehicledb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=VehicleDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  vehicles.api:
    container_name: vehicles.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "PostgresSettings:ConnectionString=Server=vehicledb;Port=5432;Database=VehicleDb;User Id=admin;Password=admin1234;"
    depends_on:
      - vehicledb
    ports:
      - "8002:80"

  vehicles.grpc:
    container_name: vehicles.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=vehicledb;Port=5432;Database=VehicleDb;User Id=admin;Password=admin1234;"
    depends_on:
      - vehicledb
    ports:
      - "8003:80"


  bikedb:
    container_name : bikedb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=BikeDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_bike_data:/var/lib/postgresql/data/

  pgadmin_bike:
    container_name: pgadmin_bike
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5051:80"
    volumes:
      - pgadmin_bike_data:/root/.pgadmin

  bikes.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "PostgresSettings:ConnectionString=Server=bikedb;Port=5432;Database=BikeDb;User Id=admin;Password=admin1234;"
    depends_on:
      - bikedb
    ports:
      - "8503:80"
